name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core utilities
  http: ^1.2.2
  provider: ^6.1.1
  intl: ^0.19.0

  # Storage & env
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.2.2
  path: ^1.9.0
  sqflite: ^2.3.2

  # UI and routing
  go_router: ^14.3.0
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

  # Auth providers
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
